server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ejeonline/spring-cloud-study.git
          search-paths: config/chapter6
          #\u516C\u5171\u4ED3\u5E93\u53EF\u4E0D\u7528\u914D\u7F6E\u5E10\u53F7\u5BC6\u7801
          username:
          password:

